archive:
  type: "s3"
  # S3 backend
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "archive"
  chunksize: 32
  # posix backend
  location: "/tmp"

backup:
  type: "s3"
  # S3 backend
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 5
  # posix backend
  #location: "dev_utils"
  #copyHeader: "true"
  #  # sftp backend
  # sftp:
  #   host: "localhost"
  #   port: "6222"
  #   userName: "user"
  #   pemKeyPath: "/keys-sftp/sftp-key.pem"
  #   pemKeyPass: "test"

broker:
  host: "rabbitmq"
  port: 5672
  user: "test"
  password: "test"
  vhost: "sda"
  queue: "error"
  exchange: "sda"
  routingKey: ""
  routingError: ""
  ssl: "false"
  verifyPeer: "false"
  clientCert: "test"
  clientKey: "test"

c4gh:
  passphrase: "repoPass"
  filepath: "/keys/repo.sec.pem"
  syncPubKeyPath: "/keys/finnish-repo.pub.pem"

db:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "rootpasswd"
  database: "sda"
  sslmode: "disable"

inbox:
  type: "s3"
  # S3 backend
  url: "http://s3"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 32
  # posix backend
  #location: "dev_utils"

log:
  level: "debug"
  format: "json"

# sync:
#   host: "http://syncapifin"
#   port: "8080"
#   password: "pass"
#   user: "dummy"

sync:
  api:
    password: "pass"
    user: "user"
  centerPrefix: "SYNC"
  destination:
    type: "s3"
    url: "http://s3fin"
    port: 9000
    readypath: "/minio/health/ready"
    accessKey: "access"
    secretKey: "secretkey"
    bucket: "sync"
    region: "us-east-1"
  remote:
    host: "http://sync-apifin"
    port: "8090"
    password: "pass"
    user: "user"